### ISSUE TITLE
started getting failure to notify

### ISSUE THREAD

**Issue by TD-4242** [svanzoest-cookbooks/sysctl#53]
With the upgrade from 0.7.2 - 0.7.4 our build/test system started dying on the following error.  Doing a role back to 0.7.2 fixes it.

```
    ================================================================================
    Error executing action `apply` on resource 'sysctl_param[vm.swappiness]'
    ================================================================================

    Chef::Exceptions::ResourceNotFound
    ----------------------------------
    resource execute[sysctl[vm.swappiness]] is configured to notify resource ruby_block[save-sysctl-params] with action run, but ruby_block[save-sysctl-params] cannot be found in the resource collection. execute[sysctl[vm.swappiness]] is defined in /var/chef/cache/cookbooks/sysctl/providers/param.rb:23:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/hadoop/recipes/_system_tuning.rb

     25: sysctl_param 'vm.swappiness' do
     26:   value 0
     27: end
     28:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/hadoop/recipes/_system_tuning.rb:25:in `from_file'

    sysctl_param("vm.swappiness") do
      action [:apply]
      updated true
      updated_by_last_action true
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :sysctl_param
      cookbook_name "hadoop"
      recipe_name "_system_tuning"
      value 0
      key "vm.swappiness"
    end
```

**Comment by svanzoest** [comment]
Please see #51

**Comment by TD-4242** [comment]
ok defaulting to that issue
